### PR TITLE
Added static swagger-ui avoiding JS dependency changes in main JSGUI

### PR DESCRIPTION
**Pull request by m4rkmckenna**

### CODE REVIEW

**Comment by ahgittin** [comment]
@m4rkmckenna cool. a few comments:
* we need to clearly differentiate what items we get from swagger and what changes we make; maybe by us owning `/assets/swagger-apidoc.html` and everything under `/assets/swagger-ui/` being an *exact* copy of swagger ui
* where you've added the rat exclude, add a comment saying it is an exact copy
* why change the indentation of the pom comment?  all the other license preambles have 4 spaces.
* the swagger references in `jsgui/.../source-inclusions.yaml` and in `usage/dist/licensing/overrides.yaml` need updating
* remove the old swagger files and references (maybe that's already been done)

also:
* can you attach a screenshot to this issue for early feedback?  mainly, is there a "back" button?
* when we discussed it was to add to the `/docs/guide` rather than in the product; i guess we no longer have to with this change, but what would be the effort involved to do so?  (personally i think it's worth it.)

**Comment by m4rkmckenna** [comment]
1. I will amend the html
2. will add a comment
3. Formatter is incorrectly setup (my bad) ... ill fix
4. Will update licence
5. Will remove old swagger files
6. Ive forced swagger-ui to open in a separate tab so no need for a back button (as JSGUI will still be open) will attach 
7. If we were to include swagger-ui as is you will hit the JS same origin policy. I looked into swagger-codegen but it will be hard to make it match the brooklyn doc style

**Comment by m4rkmckenna** [comment]
Screen cap of Brooklyn swagger-ui

screen shot 2015-11-17 at 18 07 28

**Comment by ahgittin** [comment]
6 - cool. clever simple solution.

7 - for docs can we configure it not to be an interactive ui (user can't
construct custom rest) and if the json is static on the same server it
should be fine no?

**Comment by m4rkmckenna** [comment]
If JSON is static and no calls are being made to the API then no issue with same origin

**Comment by CMoH** [comment]
I've quickly tested it, and it works perfectly.

The swagger team provides a sample servlet filter that can help with the JS same origin problem:

**Pull request merged**
